[build]
  publish = "public"
  command = "make build"

[build.environment]
  DJANGO_SETTINGS_MODULE = "omninepse.settings"
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
